interface Env {
  DB: D1Database;
  BANKROLL_CENTS?: string;
  MAX_DAILY_SPEND_CENTS?: string;
  MAX_TOTAL_LOSS_CENTS?: string;
  AUTOMATION_MODE?: string;
  ADMIN_SECRET?: string;
  META_ENABLED?: string;
  META_ACCESS_TOKEN?: string;
  META_AD_ACCOUNT_ID?: string;
  META_API_VERSION?: string;
  META_PAGE_ID?: string;
  META_PIXEL_ID?: string;
  AFFILIATE_URL?: string;
  OFFER_NAME?: string;
  OFFER_DESCRIPTION?: string;
  WHATSAPP_NUMBER?: string;
}

type OfferType = 'affiliate' | 'lead' | 'service' | 'digital';
type Offer = { id:string; type:OfferType; name:string; description:string; cta:string; url?:string };

const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=UTF-8'}});
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const config=(env:Env)=>({bankroll:Number(env.BANKROLL_CENTS||200000),maxDailySpend:Number(env.MAX_DAILY_SPEND_CENTS||50000),maxTotalLoss:Number(env.MAX_TOTAL_LOSS_CENTS||200000),automationMode:env.AUTOMATION_MODE||'approval_required',metaEnabled:env.META_ENABLED==='true',affiliateConfigured:Boolean(env.AFFILIATE_URL),whatsappConfigured:Boolean(env.WHATSAPP_NUMBER),adminConfigured:Boolean(env.ADMIN_SECRET)});

function offers(env:Env):Offer[]{const list:Offer[]=[];if(env.AFFILIATE_URL)list.push({id:'affiliate-1',type:'affiliate',name:env.OFFER_NAME||'Recommended service',description:env.OFFER_DESCRIPTION||'Explore this offer and see whether it is right for you.',cta:'Learn more',url:env.AFFILIATE_URL});list.push({id:'lead-1',type:'lead',name:'Get a free growth audit',description:'See how Meta Ads and WhatsApp can help your business generate more enquiries.',cta:'Get free audit'});list.push({id:'service-1',type:'service',name:'Get a custom growth quote',description:'Request a quote for Meta Ads, lead generation, WhatsApp growth or AI automation.',cta:'Get a quote'});list.push({id:'digital-1',type:'digital',name:'Digital toolkit',description:'A product slot that stays offline until a real product and payment flow are configured.',cta:'View toolkit'});return list;}

function landingPage(env:Env,requestUrl:URL){const cards=offers(env).map(o=>`<article class="card"><span class="tag">${esc(o.type)}</span><h2>${esc(o.name)}</h2><p>${esc(o.description)}</p><a class="cta" href="/offer/${o.id}${requestUrl.search}">${esc(o.cta)}</a>${o.type==='affiliate'?'<p class="note">Affiliate disclosure: we may earn a commission if you purchase through this link, at no extra cost to you.</p>':''}</article>`).join('');return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>NIKKSORA — Turn Attention Into Growth</title><style>body{font-family:system-ui;max-width:1000px;margin:0 auto;padding:24px 18px;background:#f7f7f7;color:#111}.hero{padding:28px 0}.hero h1{font-size:42px;margin:0 0 8px}.hero p{font-size:18px;color:#555}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.card{background:#fff;border:1px solid #ddd;border-radius:18px;padding:22px;box-shadow:0 8px 30px #0000000d}.tag{font-size:12px;text-transform:uppercase;color:#666;font-weight:700;letter-spacing:.08em}.card h2{margin:8px 0}.card p{font-size:16px;line-height:1.5;color:#444}.cta{display:inline-block;background:#111;color:#fff;text-decoration:none;padding:12px 16px;border-radius:10px;font-weight:700;margin-top:6px}.note{font-size:12px!important;color:#777!important;margin-top:16px}</style></head><body><main><section class="hero"><h1>NIKKSORA</h1><p><strong>Turn Attention Into Growth.</strong><br>Meta Ads • WhatsApp Growth • Lead Generation • AI Automation</p></section><section class="grid">${cards}</section></main></body></html>`;}

function leadForm(title:string,kind:string,requestUrl:URL){const campaign=requestUrl.searchParams.get('campaign')||'';return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — NIKKSORA</title><style>body{font-family:system-ui;max-width:680px;margin:0 auto;padding:28px 18px;background:#f7f7f7}.card{background:#fff;border:1px solid #ddd;border-radius:18px;padding:26px;margin-top:8vh}label{display:block;font-weight:650;margin:14px 0 6px}input,textarea{width:100%;box-sizing:border-box;padding:12px;border:1px solid #bbb;border-radius:9px;font:inherit}textarea{min-height:120px}.cta{margin-top:18px;background:#111;color:#fff;border:0;padding:13px 18px;border-radius:10px;font-weight:700}.note{font-size:12px;color:#666;line-height:1.5}</style></head><body><main class="card"><h1>${esc(title)}</h1><form method="post" action="/api/leads"><input type="hidden" name="kind" value="${esc(kind)}"><input type="hidden" name="campaign" value="${esc(campaign)}"><label>Name</label><input name="name" required maxlength="120"><label>Business name</label><input name="business" maxlength="160"><label>Phone or WhatsApp</label><input name="phone" required maxlength="40"><label>What is your biggest marketing problem?</label><textarea name="message" maxlength="1000"></textarea><label><input type="checkbox" name="consent" value="yes" required> I agree to be contacted about this request.</label><button class="cta" type="submit">Submit request</button></form><p class="note">NIKKSORA uses the information you submit only to respond to your request and provide the requested service.</p></main></body></html>`;}

async function ensureSchema(env:Env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,campaign_id TEXT,amount_cents INTEGER NOT NULL DEFAULT 0,metadata TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS events_created_at_idx ON events(created_at)`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS events_campaign_idx ON events(campaign_id)`).run();}
async function totals(env:Env){await ensureSchema(env);const r=await env.DB.prepare(`SELECT COALESCE(SUM(CASE WHEN type='spend' THEN amount_cents ELSE 0 END),0) spend,COALESCE(SUM(CASE WHEN type='commission' THEN amount_cents ELSE 0 END),0) commission,COALESCE(SUM(CASE WHEN type='revenue' THEN amount_cents ELSE 0 END),0) revenue,SUM(CASE WHEN type='lead' THEN 1 ELSE 0 END) leads,SUM(CASE WHEN type='sale' THEN 1 ELSE 0 END) sales,SUM(CASE WHEN type='click' THEN 1 ELSE 0 END) clicks,SUM(CASE WHEN type='impression' THEN 1 ELSE 0 END) impressions FROM events`).first<Record<string,number>>();const revenue=Number(r?.revenue||0)+Number(r?.commission||0);return{spend:Number(r?.spend||0),commission:Number(r?.commission||0),revenue,leads:Number(r?.leads||0),sales:Number(r?.sales||0),clicks:Number(r?.clicks||0),impressions:Number(r?.impressions||0)};}
function decision(t:{spend:number;revenue:number;sales:number;leads:number},c:ReturnType<typeof config>){const profit=t.revenue-t.spend;const roas=t.spend?t.revenue/t.spend:null;if(t.spend>=c.maxTotalLoss)return{action:'PAUSE_ALL',reason:'Total loss cap reached'};if(t.spend>=c.bankroll)return{action:'PAUSE_ALL',reason:'Bankroll ceiling reached'};if(profit<0&&t.spend>=c.maxDailySpend)return{action:'PAUSE_LOSERS',reason:'Negative result after test budget'};if(t.sales>=3&&profit>0&&roas!==null&&roas>=1.5)return{action:'SCALE_CANDIDATE',reason:'Positive profit with sufficient sales'};if(t.leads>=5&&profit>0)return{action:'SCALE_CANDIDATE',reason:'Lead funnel is producing positive measured revenue'};return{action:'HOLD',reason:'Need more data before changing spend'};}
async function recordEvent(env:Env,type:string,campaignId:string|null,amountCents:number,metadata:Record<string,unknown>={}){await ensureSchema(env);await env.DB.prepare('INSERT INTO events(type,campaign_id,amount_cents,metadata) VALUES(?,?,?,?)').bind(type,campaignId,amountCents,JSON.stringify(metadata)).run();}
function authorized(request:Request,env:Env){return Boolean(env.ADMIN_SECRET)&&request.headers.get('x-admin-secret')===env.ADMIN_SECRET;}

export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);
if(url.pathname==='/')return new Response(landingPage(env,url),{headers:{'content-type':'text/html; charset=UTF-8'}});
if(url.pathname==='/dashboard'){const dashboard=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>NIKKSORA Dashboard</title><style>body{font-family:system-ui;max-width:1050px;margin:30px auto;padding:0 18px;background:#f7f7f7}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px}.card{background:#fff;border:1px solid #ddd;border-radius:14px;padding:16px}.value{font-size:24px;font-weight:750;margin-top:5px}button,input{padding:10px 14px;border-radius:9px;border:1px solid #aaa;background:#fff}pre{background:#111;color:#eee;padding:16px;border-radius:12px;overflow:auto}</style></head><body><h1>NIKKSORA</h1><p>Revenue engine — Meta Ads, leads, services and digital funnels.</p><input id="secret" type="password" placeholder="Admin secret"><button onclick="load()">Load</button><div class="grid" id="cards"></div><pre id="decision">Enter admin secret to load private metrics.</pre><script>async function load(){const s=document.getElementById('secret').value;try{const r=await fetch('/api/admin/summary',{headers:{'x-admin-secret':s}});const m=await r.json();if(!r.ok)throw Error(m.error||'Unauthorized');const labels=[['Spend',m.spend],['Revenue',m.revenue],['Profit',m.profitCents],['Leads',m.leads],['Sales',m.sales],['Clicks',m.clicks],['ROAS',m.roas??'-']];document.getElementById('cards').innerHTML=labels.map(x=>'<div class="card"><div>'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join('');document.getElementById('decision').textContent=JSON.stringify(m,null,2)}catch(e){document.getElementById('decision').textContent=e.message}}</script></body></html>`;return new Response(dashboard,{headers:{'content-type':'text/html; charset=UTF-8'}});}
if(url.pathname==='/health'){try{await ensureSchema(env);return json({ok:true,service:'nikksora',runtime:'cloudflare-worker',database:'d1'});}catch{return json({ok:false,service:'nikksora',runtime:'cloudflare-worker',database:'d1-unavailable'},503);}}
if(url.pathname==='/api/config'&&request.method==='GET')return json({...config(env),moneyMovingActionsRequireApproval:true,database:'d1',monetizationModes:['affiliate','lead','service','digital']});
if(url.pathname==='/api/metrics'&&request.method==='GET'){try{const t=await totals(env);const profit=t.revenue-t.spend;return json({...t,profitCents:profit,cpaCents:t.leads?Math.round(t.spend/t.leads):null,roas:t.spend?Number((t.revenue/t.spend).toFixed(2)):null,decision:decision(t,config(env)),bankrollRemainingCents:Math.max(0,config(env).bankroll-t.spend)});}catch{return json({error:'Failed to calculate metrics'},500);}}
if(url.pathname==='/api/admin/summary'&&request.method==='GET'){if(!authorized(request,env))return json({error:'Unauthorized'},401);const t=await totals(env);return json({...t,profitCents:t.revenue-t.spend,roas:t.spend?Number((t.revenue/t.spend).toFixed(2)):null,decision:decision(t,config(env)),bankrollRemainingCents:Math.max(0,config(env).bankroll-t.spend)});}
if(url.pathname==='/api/admin/leads'&&request.method==='GET'){if(!authorized(request,env))return json({error:'Unauthorized'},401);await ensureSchema(env);const rows=await env.DB.prepare(`SELECT id,campaign_id,metadata,created_at FROM events WHERE type='lead' ORDER BY id DESC LIMIT 100`).all();return json({leads:rows.results});}
if(url.pathname.startsWith('/offer/')&&request.method==='GET'){const id=url.pathname.slice('/offer/'.length);const offer=offers(env).find(o=>o.id===id);if(!offer)return json({error:'Offer not found'},404);const campaign=url.searchParams.get('campaign');await recordEvent(env,'click',campaign,0,{offerId:offer.id,offerType:offer.type});if(offer.type==='affiliate'&&offer.url)return Response.redirect(offer.url,302);if(offer.type==='lead')return new Response(leadForm('Get a free growth audit','lead',url),{headers:{'content-type':'text/html; charset=UTF-8'}});if(offer.type==='service')return new Response(leadForm('Get a custom growth quote','service',url),{headers:{'content-type':'text/html; charset=UTF-8'}});return new Response('<!doctype html><html><body style="font-family:system-ui;max-width:680px;margin:40px auto;padding:20px"><h1>Digital toolkit coming soon</h1><p>This slot is not live until a real product and payment/delivery flow are configured.</p></body></html>',{headers:{'content-type':'text/html; charset=UTF-8'}});}
if(url.pathname==='/go'&&request.method==='GET'){if(!env.AFFILIATE_URL)return json({error:'Affiliate URL not configured'},503);await recordEvent(env,'click',url.searchParams.get('campaign')||null,0,{offerId:'affiliate-1',offerType:'affiliate'});return Response.redirect(env.AFFILIATE_URL,302);}
if(url.pathname==='/lead'&&request.method==='GET')return new Response(leadForm('Get a free growth audit','lead',url),{headers:{'content-type':'text/html; charset=UTF-8'}});
if(url.pathname==='/service'&&request.method==='GET')return new Response(leadForm('Get a custom growth quote','service',url),{headers:{'content-type':'text/html; charset=UTF-8'}});
if(url.pathname==='/whatsapp'&&request.method==='GET'){if(!env.WHATSAPP_NUMBER)return json({error:'WhatsApp number not configured'},503);const campaign=url.searchParams.get('campaign');await recordEvent(env,'click',campaign||null,0,{offerId:'whatsapp',offerType:'lead'});const message=encodeURIComponent('Hi, I found NIKKSORA and would like a free growth audit.');return Response.redirect(`https://wa.me/${env.WHATSAPP_NUMBER.replace(/\D/g,'')}?text=${message}`,302);}
if(url.pathname==='/api/leads'&&request.method==='POST'){const form=await request.formData().catch(()=>null);if(!form)return json({error:'Invalid form'},400);const name=String(form.get('name')||'').trim();const business=String(form.get('business')||'').trim();const phone=String(form.get('phone')||'').trim();const message=String(form.get('message')||'').trim();const kind=String(form.get('kind')||'lead');const campaign=String(form.get('campaign')||'')||null;if(!name||!phone||form.get('consent')!=='yes')return json({error:'Name, phone and consent are required'},400);await recordEvent(env,'lead',campaign,0,{kind,name,business,phone,message,consent:true});return new Response('<!doctype html><html><body style="font-family:system-ui;max-width:680px;margin:40px auto;padding:20px"><h1>Request received</h1><p>Thanks. NIKKSORA received your request and will follow up.</p></body></html>',{headers:{'content-type':'text/html; charset=UTF-8'}});}
if(url.pathname==='/api/events'&&request.method==='POST'){if(!authorized(request,env))return json({error:'Unauthorized'},401);const body=await request.json().catch(()=>null) as {type?:string;campaignId?:string;amount?:number;metadata?:object}|null;if(!body||!['spend','commission','revenue','sale','click','impression','lead'].includes(body.type||''))return json({error:'Invalid event type'},400);const type=body.type!;const amountCents=(type==='click'||type==='impression'||type==='lead'||type==='sale')?0:Math.round(Number(body.amount||0)*100);if(!Number.isFinite(amountCents)||amountCents<0)return json({error:'Invalid amount'},400);await recordEvent(env,type,body.campaignId||null,amountCents,(body.metadata||{}) as Record<string,unknown>);return json(await totals(env),201);}
return json({error:'Not found'},404);}};